version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - npm run package
artifacts:
  type: zip
  files:
    - packaged-template.yaml